In [1]:
import h5py
import numpy as np

#### data

In [2]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [3]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [4]:
c = np.eye(2)
c

array([[1., 0.],
       [0., 1.]])

#### write

In [5]:
h5py_filepath = "h5py.hdf5"

In [6]:
with h5py.File(h5py_filepath, 'w') as f:
    dataset = f.create_dataset("a", a.shape, dtype=a.dtype, compression='gzip')
    dataset[:] = a
    dataset = f.create_dataset("b", b.shape, dtype=b.dtype, compression='gzip')
    dataset[:] = b
    dataset = f.create_dataset("c", c.shape, dtype=c.dtype, compression='gzip')
    dataset[:] = c

#### read

In [7]:
with h5py.File(h5py_filepath, 'r') as f:
    a = np.array(f['a'])
    b = np.array(f['b'])
    c = np.array(f['c'])

In [8]:
a

array([[0., 0.],
       [0., 0.]])

In [9]:
b

array([[1., 1.],
       [1., 1.]])

In [10]:
c

array([[1., 0.],
       [0., 1.]])