In [1]:
import numpy as np
from scipy.spatial.distance import squareform, cdist, pdist

### size

In [2]:
a = np.array((1, 2, 3))
a

array([1, 2, 3])

In [3]:
len(a)

3

In [4]:
a.shape

(3,)

In [5]:
a.ndim

1

### type

In [6]:
a.dtype

dtype('int64')

In [7]:
a = np.array(a, dtype=float)
a.dtype

dtype('float64')

In [8]:
a = np.array(a, dtype=complex)
a.dtype

dtype('complex128')

In [9]:
c = np.array([1 + 2j, 3 + 4j])
c.dtype

dtype('complex128')

In [10]:
l = np.array([True, False, True, False])
l.dtype

dtype('bool')

In [11]:
s = np.array(['firstname', 'lastname'])
s.dtype

dtype('<U9')

In [12]:
b = np.array((4., 5., 6.))
b.dtype

dtype('float64')

### joining

In [13]:
c = np.vstack((a, b))
c

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [14]:
d = np.hstack((a, b))
d

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

In [15]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[10, 20, 30], [40, 50, 60]])
z = np.concatenate((x, y), axis=1)
z

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

In [16]:
u = np.array([[1], [2], [3]])
v = np.array([[4], [5], [6]])
w = np.concatenate((u, v), axis=1)
w

array([[1, 4],
       [2, 5],
       [3, 6]])

In [17]:
w[:, 0]

array([1, 2, 3])

In [18]:
partition = (np.max(w, axis=0) - np.min(w, axis=0)) / 2
overlap = partition * 0.2
overlap

array([0.2, 0.2])

### slicing

In [19]:
d[0], d[1], d[2]

((1+0j), (2+0j), (3+0j))

In [20]:
d[0:10:2]

array([1.+0.j, 3.+0.j, 5.+0.j])

In [21]:
d[::-1]

array([6.+0.j, 5.+0.j, 4.+0.j, 3.+0.j, 2.+0.j, 1.+0.j])

In [22]:
d[0:5] = 10
d

array([10.+0.j, 10.+0.j, 10.+0.j, 10.+0.j, 10.+0.j,  6.+0.j])

### creating custom

In [23]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
b = np.arange(0, 10, 2)
b

array([0, 2, 4, 6, 8])

In [25]:
c = np.linspace(0, 1, 10)
c

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [26]:
d = np.linspace(0, 1, 10, endpoint=False)
d

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [27]:
d = np.linspace(0, 1, 10, endpoint=True)
d

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

### creating generics

In [28]:
e = np.empty(5)
e

array([0. , 0.5, 1. , 1.5, 2. ])

In [29]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [30]:
b = np.ones((2, 2))
b

array([[1., 1.],
       [1., 1.]])

In [31]:
c = np.eye(2)
c

array([[1., 0.],
       [0., 1.]])

In [32]:
d = np.array([1, 2, 3, 4])
m = np.diag(d)
m

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [33]:
m[3, 3]

4

In [34]:
m[:2, :]

array([[1, 0, 0, 0],
       [0, 2, 0, 0]])

### creating random

In [35]:
seed = 0
np.random.seed(seed)

In [36]:
# uniform distribution
a = np.random.rand(10)
a

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [37]:
# normal distribution
b = np.random.randn(10)
b

array([ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323,
        0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574])

In [38]:
c = np.random.randint(0, 10, 100)
c

array([9, 9, 0, 4, 7, 3, 2, 7, 2, 0, 0, 4, 5, 5, 6, 8, 4, 1, 4, 9, 8, 1,
       1, 7, 9, 9, 3, 6, 7, 2, 0, 3, 5, 9, 4, 4, 6, 4, 4, 3, 4, 4, 8, 4,
       3, 7, 5, 5, 0, 1, 5, 9, 3, 0, 5, 0, 1, 2, 4, 2, 0, 3, 2, 0, 7, 5,
       9, 0, 2, 7, 2, 9, 2, 3, 3, 2, 3, 4, 1, 2, 9, 1, 4, 6, 8, 2, 3, 0,
       0, 6, 0, 6, 3, 3, 8, 8, 8, 2, 3, 2])

### masking

In [39]:
even_mask = (c%2 == 0)
even_mask

array([False, False,  True,  True, False, False,  True, False,  True,
        True,  True,  True, False, False,  True,  True,  True, False,
        True, False,  True, False, False, False, False, False, False,
        True, False,  True,  True, False, False, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True, False,
       False, False, False,  True, False, False, False, False,  True,
       False,  True, False,  True,  True,  True,  True, False,  True,
        True, False, False, False,  True,  True, False,  True, False,
        True, False, False,  True, False,  True, False,  True, False,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True, False, False,  True,  True,  True,  True, False,
        True])

In [40]:
even = c[even_mask]
even

array([0, 4, 2, 2, 0, 0, 4, 6, 8, 4, 4, 8, 6, 2, 0, 4, 4, 6, 4, 4, 4, 4,
       8, 4, 0, 0, 0, 2, 4, 2, 0, 2, 0, 0, 2, 2, 2, 2, 4, 2, 4, 6, 8, 2,
       0, 0, 6, 0, 6, 8, 8, 8, 2, 2])

### behind the scene

In [41]:
x = c[:5]
x

array([9, 9, 0, 4, 7])

In [42]:
np.may_share_memory(c, x)

True

In [43]:
y = c[:5].copy()
y

array([9, 9, 0, 4, 7])

In [44]:
np.may_share_memory(c, y)

False

In [45]:
z = c[[0,1,2,3,4]]
z

array([9, 9, 0, 4, 7])

In [46]:
np.may_share_memory(c, z)

False